name: Playwright Tests
on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

env:
  PLAYWRIGHT_TEST_BASE_URL: "https://deploy-preview-${{github.event.pull_request.number}}--postscript-medical.netlify.app"
  PERCY_TOKEN: ${{secrets.PERCY_TOKEN}}

jobs:
  test_netlify_prepare:
    name: Wait for deployment on Netlify
    runs-on: ubuntu-latest
    steps:
    - name: Waiting for Netlify Preview
      uses: jakepartusch/wait-for-netlify-action@v1.4
      id: wait-for-netflify-preview
      with:
        site_name: "staging-app-postscriptmedical"
        max_timeout: 180

  tests_netlify:
    needs: test_netlify_prepare
    name: Run end-to-end tests on Netlify PR preview
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npm run test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
